# User Stories and Use Cases

<!-- Notas: -->

<!-- Poder conocer las preguntas generales y la útilidad. Expertos de EC puedan saber de que trata sin ir al detalle o tener que compartir la propuesta. -->

<!-- Descripción de los use cases pero no llegar a explicar la implementación/propuesta/detalle. Por ejemplo la figura 4.1 potser es massa detallada. POsar-ho un nou apartat al final: on estem i detall. -->

<!-- Importante poder vislumbrar que building blocks, conditions or capabilities van a ser necesarias para poder implementarlo -->

<!-- Mirar document sobre w3i: Explicar les funcionalitats/requeriments i casos d'us. -->

## Introduction

### What is a User Story and a Use Case

Is a User Story the same thing as a Use Case? Although there are some similarities between User Stories and Use Cases, User Stories and Use Cases are not interchangeable; both User Stories and Use Cases identify users and they both describe goal, but they serve different purposes.

A **user story** is an informal, natural language description of features of a software system. They are written from the perspective of an end user or user of a system. A User Story is a note that captures what a user does or needs to do as part of her work. Each User Story consists of a short description written from user's point of view, with natural language. Unlike the traditional requirement capturing, User Story focuses on what the user needs instead of what the system should deliver. This leaves room for further discussion of solutions and the result of a system that can really fit into the customers' business workflow, solving their operational problems and most importantly adding value to the organization.

A **Use case** is used to capture user (actor) point of view while describing functional requirements of the system. They describe the step by step process a user goes through to complete that goal using a software system. A Use Case is a description of all the ways an end-user wants to "use" a system. Use Cases capture all the possible ways the user and system can interact that result in the user achieving the goal. They also capture all the things that can go wrong along the way that prevent the user from achieving the goal.

### Similarity between User Stories vs Use Cases

If we consider the key component in both approaches:

-   User Stories contain, with user role, goal and acceptance criteria.

-   Use Cases contain equivalent elements: an actor, flow of events and post conditions respectively

### Diferences between User Stories vs Use Cases

User Stories are centered on the result and the benefit of the thing you're describing, whereas Use Cases can be more granular, and describe how your system will act. The details of a User Story may not be documented to the same extreme as a Use Case.

-   User Stories deliberately leave out a lot of important details. User Stories are meant to elicit conversations by asking questions during scrum meetings.

-   Small increments for getting feedback more frequently, rather than having more detailed up-front requirement specification as in Use Cases.

> User stories don't provide the details the development team needs to do their work.

<!-- > In a Use case Who is the lead beneficiary of the solution? Explain the type of users that would benefit from the solution. Explain the solution, what problem does it solve, and what is the intended user experience. For example, you could use the use case from the view of the user, as if it was a testimonial: As a (user) \_\_\_ I Can (action) \_\_\_\_ So that (value for the user) \_\_\_\_ -->



## Use cases

> User Stories contain, with user role, goal and acceptance criteria.

> User Story focuses on what the user needs instead of what the system should deliver

### Use Case: Producer responsibility organization - reporting of e-waste

user roles: supplier, producer responsibility organizations, refurbishers, recycler, Final User, collection point and auditors.
goals: reporting preparation for reuse and e-waste management, devices are considered ewaste in the supplier

Un **supplier** (Productor de residuos de (ej: Movistar)) contrata a un **producer responsibility organizations** (PRO, ej: Ecoasimelec) para la gestión de los dispositivos usados que tiene en propiedad o de sus clientes. Estos dispositivos estan en contenedores ubicados en sus tiendas. El PRO contrata a **refurbishers** [de tipo gestores de preparación para la reutilización] autorizadas por las comunidades autónomas. Las **refurbishers** (ej: Andròmines) recojen los contenedores de las tiendas y hacen un proceso de selección. Los dispositivos reutilizables se reparan/mejoran y venden de segunda mano a **final users** y los no reutilizables se depositan en contenedores para transferirse a **recyclers** de tratamiento (ej: electrorecycling), y estos los mandan a las refinerias que recuperan las materias primeras. A los dispositivos de segunda mano se crea un Digital Product Passport con la descripción del producto, los componentes y las pruebas de funcionamiento realizadas. Los **Final users** (consumidores de segunda mano) deben poder acceder de manera online a este documento generado por las reacondicionadoras y poder verificar que se ha generado con software acreditado.  Los dispositivos en reutilización cuando llegan al final de su vida deben terminar en un **collection point** (punto limpio/verde/deixallería) por lo que los Final Users deben poder transferirlos a una de estas instalaciones. La información del impacto generado en economía circular, la cadena de custodia y las credenciales de sus participantes debe poder verificarse por parte del los participantes y **auditors** preservando la privacidad.

### Use Case: Refurbisher - impact accounting and reporting

user roles: refurbishers, suppliers (of unused devices), recycler, Final User.
goals: report lifetime extension and final recycling, devices are considered products by the supplier and the refurbisher.

Refurbishers are business collecting used devices, repairing and reselling them.

El **refurbisher** Andròmines recibe dispositivos usados de un **supplier** de dispositivos usados (i.e: Ayuntamiento de Barcelona) que quiere que sus dispositivos se reutilizen y reciclen de manera adecuada. El refurbisher recoje y hace un inventario de los dispositivos y los filtra según potencial de reutilización. Los que tienen un potencial de reutilización bajo los mandará a un **reciclador** que los desmantela y manda a una fundición, los que son reutilizables los venderá/donará a **Final users** para que sean reutilizados. El objetivo del refurbisher es poder reportar a su supplier el impacto generado en economía circular (ver annexos - Report on IT deed of assignment - reuse and recycling progress) que principalmente es el tiempo de extensión de vida del dispositivo y su reciclaje final por parte de un reciclador autorizado. En cuanto a contabilizar el impacto la dificultades para el refurbisher son: 1) poder saber si los Final Users después de su reutilización han llevado a un punto autorizado de reciclaje el dispositivo, 2) saber si los recicladores a los que manda lo que no es potencialmente reutilizable estan autorizados por las autoridades competentes y saber si se han reciclado 3) saber durante cuantas horas y años se han reutilizado los dispositivos. Esta información debería ser verificable y auditable por parte del refurbisher, suppliers y auditores a los que el refurbisher se lo permita. Entendemos por verificable la posibilidad de tener la certeza que en una transferencia de dispositivos las dos partes han participado (confirmando) y que se han transferido unos dispositivos con una identidad única. 

Testimonials:

> As a (user) \_\_\_ I Can (action) \_\_\_\_ So that (value for the user) \_\_\_\_

As a refurbisher I can :

1. Puedo saber las horas de extensión de tiempo de vida de los dispositivos que di a un reseller o a un Final user

2. Puedo saber si los Final Users han reciclado los dispositivos al final de su tiempo de vida útil

3. Puedo generar un informe de cadena de custódia que ... y cada transferencia es verificable

4. Puedo generar un informe de impacto agregado y el impacto de cada device puede ser conocido

Ejemplo: De los 100 dispositivos que el donante me dió puedo saber:
    -   70 se han reutilizado por parte de usuarios finales que han extendido el tiempo de vida en X horas y 30 se han reciclado sin reutilización por tal usuario
    -   de 70 reutilizados se tenemos conformidad del reciclaje de 30 de ellos y se han reciclado por estos usuarios (no hace falta que sea anónimo)


### Use Case : Refurbisher - seller of second-hand devices

user roles: refurbishers, resellers and Final User.
goals: report the refurbishment process and quality of second hand devices refurbished

El **refurbisher** Solidança ha reacondicionado (reparación / upgrade / install SO) un conjunto de dispositivos. Quiere poder informar a sus potenciales compradores que son **resellers** (B2B) o **Final Users** (B2C) de: 1) la identidad del dispositivo y una descripción de los componentes que incluye, 2) el proceso de reacondicionado (borrado de datos, tests,.....). El refurbisher debe poder mandar esta información a sus potenciales compradores mediante web o documentos y estos poder verificar que esta información es creible, entendido como: 1) se ha generado mediante herramientas software sin manipulación, 2) se generó en una fecha determinada. Además, el comprador al recibir el dispositivo debe poder usar unas tools software que le aseguren que es la misma identidad y descripción.

Testimonials:

> As a (user) \_\_\_ I Can (action) \_\_\_\_ So that (value for the user) \_\_\_\_

As a refurbisher with role (seller) of refurbished devices I can :

1. Puedo generar un documento (pdf, url) con la identidad del dispositivo y los componentes que incluye

2. Puedo generar un documento (pdf, url) con el proceso de reacondicionado y las pruebas realizadas, especialmente el borrado de datos y el test de disco y de stress.

As a Final User with role (buyer) I can:

1. Verificar que el dispositivo que tengo físicamente es un dispositivo virtual 

2. Tener la garantía que la información se ha generado con un software y que no ha sido modificada de manera manual.

### Use Case: Supplier - Refurbishers credentials/reputation  

(ref:userstorysupplier) Citizen and professional reuse of digital devices.

User roles: Supplier and refurbisher.

Un **supplier** es una empresa o una administración pública que tiene dispositivos usados que quiere que se destinen a la reutilización. Para ellos es difícil identificar que refurbishers tienen la capacidad de poder reportar de manera fiable el impacto creado en economía circular. Quieren poder identificar quales tienen esta habilidad por lo que algun sistema de credenciales/reputación les facilitaría esta búsqueda. Otras preguntas.

What questions should we be able to answer?

-   Which refurbisher/ITAD should the Product Owner choose in order to increase the reuse and the final recycling? Are there any metrics or standarized definitions for measuring impact and comparing? see figure \@ref(fig:figreuseimpact)
-   How they can encourage refurbishers/ITADs to account the impact of reuse and report the final recycling? Is there guidelines that provide a common basis for collecting this data? are there any standarized certification, third-party analyses for concisely communicating social and/or environmental performance? Are there any instruments for facilitating the diligence, assessment, monitoring and reporting of impact?
-   How can they or third parties know with certainty that a device has been reused and recycled without requiring the actors having to disclose business information or that may penalise them negatively? so how they can verify reuse and finaly recycling.


### Resum of User needs

Resumen de las necesidades expresadas en las user stories

Se incluyen las credenciales detectadas: https://www.w3.org/TR/vc-use-cases/#user-needs

**UN.1 Suppliers and refurbishers as waste producers**

Un supplier del tipo Productor de Residuos quiere transferir un contenedor de dispositivos a una reacondicionadora de PxR. Antes de la transferencia el Productor debe de informar al gestor sus credenciales el código NIMA  (ej: 0100604396) y el gestor debe informar al Productor de su código NIMA y código de gestor (ej E-1503.15). La trazabilidad de dicha transferencia se debe consultable/verificable en la blockchain pero sin revelar los participantes ni sus códigos pero asegurando que ambos tienen las credenciales en vigor y en el caso de gestor que su código lo habilite para ser preparador para la reutilización. La blockchain debe registrar el trade de ambas partes.
    
**UN.2 Refurbishers creating creating Digital Products passports of Prepared for Reuse devices**

El refurbisher (ej: Andròmines) recoje un contenedor de dispositivos del Productor de Residuos. Hace el proceso de preparación para la reutilización (era residuo), crea un Digital Product Passport y revende/dona los dispositivos. El DPP contiene la descripción del producto, los componentes y las pruebas de funcionamiento realizadas. Los consumidores de segunda mano deben poder acceder de manera online a este documento generado por las reacondicionadoras y poder verificar que se ha generado las credenciales de un software eReuse y con las credenciales de componentes y de funcionamiento adecuado. Los consumidores tambien deben poder regenerar el DPP en caso de que se pierda la etiqueta o quieran validar que el producto que compraron es el que recibieron. 
    
**UN.3 Refurbishers transfering ewaste to Recyclers**

La reacondicionadora quiere transferir un contenedor de dispositivos a una recicladora de tratamiento. El contenedor puede tener los dispositivos desmantelados o no y debe de tener un peso. El contenedor tiene tanto dispositivos con DPP como dispositivos sin. Antes de la transferencia ambas partes deben poder acreditar a la otra de sus códigos NIMA  (ej: 0100604396) y de gestor (ej E-1503.15). La trazabilidad de dicha transferencia se debe consultable/verificable en la blockchain pero sin revelar los participantes ni sus códigos pero asegurando que ambos tienen las credenciales en vigor y que los códigos de gestores permiten la gestión de este tipo de residuos. La blockchain debe registrar el trade de ambas partes.
    
**UN.4. Final users disposing in collection points**

El consumidor final quiere llevar sus dispositivos no reutilizables a una instalaEsticción de recogida  de residuos municipal (punto limpio/verde/deixallería). El consumidor debe de poder validar de si la instalación tiene una credencial de recogida de residuos municipales. La instalación debe de poder regenerar el DPP para informar que ha recogido el DPP para así confirmar que el producto dispositivo es en realidad el DPP. La trazabilidad de dicha transferencia del consumidor a la instalación de recogida debe de ser consultable/verificable en la blockchain pero sin revelar la identidad de los participantes.

TODO: Revisar las user needs que faltan explicadas en las User stories.


## User Stories

TODO. Poner Trublo 






