# Technology

TODO: vincular los componentes software con los use cases.

Ereuse has developed software, protocol and data commons for local refurbishment ecosystems with traceability and impact accounting. Ereuse is a B2B, open-source system ready to be used and extended. The role of eReuse is to coordinate a roadmap and ensure the code is freely available to the federation of refurbishers. The software development is supported by contributions from research centres, companies and the community. 

eReuse offers a set of tools that automate the process of secure collection and traceability monitoring in the management of electronics (Workbench and Devicehub). eReuse has developed a Distributed Ledger Technology (DLT) with a block explorer in order to ensure: immutability (not being able to change the past), verifiability (being able to confirm that a fact is supported) and privacy (not showing identifiers of devices, businesses or people).

In the eReuse software every single piece of an old laptop or desktop collected from a company or a government by the refurbisher is broken down into individual pieces, recorded and indexed in a transparent and privacy-preserving database. The refurbisher repairs and rebuilds the machines, and their value and quality are reported in the system and potential customers. Refurbishers then loan the repaired machine in a second-hand market and monitor the process till every single item is correctly reused and finally recycled. As a result, eReuse systems prevent much more waste from going to landfill, extend the lifetime of digital devices and make obsolescence visible (real durability of devices in hours and reparability). This contributes to changing consumer habits and ultimately manufacturers’ policies by empowering governments, refurbishers and citizens with new DLT-based technology that provides for device traceability and impact accounting.

Until now, there has been no standard traceability protocol to assess impacts and bring transparency to the refurbishment and reuse sector of electronic devices. In the business as usual refurbishers providers have non-transparent redistribution channels based on undisclosed business relationships. This prevents impact accounting. eReuse enhances trust while conciliating business privacy. eReuse has developed a disruptive traceability & impacting accounting as a stand-alone service that can be used by existing refurbishers. eReuse enable an infraestructure to trace the reverse-chain of ownership custody, and reports data to assess social and environmental impact. 

eReuse systems are managed and governed locally by governments and business  (Product Owners) and social enterprises (Refurbishers). , and refurbishers collect, refurbish and deliver to business and citizens (Final Users) willing to reuse a second-hand device. 


## Open data 

A public dataset (1) about reuse of computing devices in eReuse under CCBY4.0 license: The original dataset has been anonymized and exported from the refurbishers’ Devicehub.

1. Data set July 2020. We have limited the study to only refurbishers with operations in Spain that has accepted the data commons license. Data collected between 2013-10-08 and 2019-06-03.
https://dsg.ac.upc.edu/sites/default/files/dsg/eReuseDataJun2019_0.html

## Open Code

The following paragraphs describe from a more technical point of view the respective components that are part of the eReuse system. We indicate the TRL level, license and its link to the code and application.

### Workbench USB

Workbench USB (TRL 8-9), AGPL-3.0, a software tool for logging, testing and erasing device data. The Workbench is run via a bootable USB stick and if the device is connected to the internet it sends the result (snapshot) to the Devicehub component (3). The time to perform the registration is less than one minute. 
Code: https://github.com/eReuse/workbench-live
Demo erase and rate: https://www.usody.com/demo-usody-free/

### Workbench network

Workbench network VirtualBox

Workbench network ISO

### Workbench desktop

Workbench Desktop (TRL 5), GPL-3.0, is a desktop cross-platform application which extracts details about the hardware of computer devices and submits a snapshot to DeviceHub with the status of functioning and the hours has been in operation. This component has been developed specifically for the DLT4EU as an alternative to using the USB Workbench for end users. 
Code:  https://github.com/eReuse/workbench-desktop

### Devicehub

Devicehub (TRL8), AGPL-3.0, a cloud-based IT asset disposition and management system where Product Owners and Refurbishers can manage device traceability, tag and exchange devices. Devicehub instances are federated and autonomous. If they want to certify impacts, they can write a timestamp of their data to the DLT (4). Devicehub is implemented as a RESTful Python 3 web application built on the open source micro-framework Teal, part of this Devicehub; built on Flask and uses the PostgreSQL database. The DeviceHub client is a browser application built in Javascript, CSS and HTML in the Angular framework. 
Code: https://github.com/eReuse/devicehub-teal
Demo: https://app.usody.com/login , user: hello@usody.com, pass: usody
 
### DLT

DLT (TRL 5), GPL-3.0, A privacy-preserving DLT only storing timestamps of reports. A frontend allows the end user to attach a CSV, create a timestamp and store it in the DLT. To ensure that the data comes from a Devicehub the frontend queries the corresponding Devicehub to check if if the timestamp is valid. If so, it is recorded in the DLT, a Permissioned Ethereum PoA. 
Frontend code, AGPL-3.0: https://github.com/DSG-UPC/reports-platform
Frontend app: https://dlt.ereuse.org/
DLT: https://github.com/DSG-UPC/eReuse-Blockchain

## Legacy

### Android APP
A smartphone and tablet Android app that has two functionalities.
Obtain metadata from devices that are not computers, like peripherals or electrical appliances, by scanning their barcodes and taking pictures from them.
Link devices with tags generated by the eReuse.org tools, like QR codes and NFC chips.

https://github.com/eReuse/ereuse-android-app
https://github.com/eReuse/ereuse-android-app/releases/latest




