---
title: "eReuse.org Whitepaper"
author: |
  | $^1$Universitat Politècnica de Catalunya
  | David Franquesa 1^[Corresponding author: david.franquesa@upc.edu], Leandro Navarro 1$^1$, y todos los que faltan!
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
subtitle: The Circular Economy of Digital Devices
documentclass: book
bibliography:
- book.bib
- packages.bib
link-citations: yes
github-repo: rstudio/bookdown-demo
site: bookdown::bookdown_site
---

```{r echo = FALSE, , include = FALSE}
path_req <- "/home/david/NextCloud/David-Tesi/eReuseMetrics/code/requirements"
source(file.path(path_req,"libraries.R"))
```


<!-- https://bookdown.org/yihui/rmarkdown/ -->

<!-- To preview on github https://htmlpreview.github.io/?https://github.com/eReuse/eReuse-whitepaper/blob/main/_book/index.html -->

<!-- rmarkdown::render(input = file.path(".","index.Rmd"), output_file =  file.path(".","_book","index"), output_format = "pdf_document", envir = new.env()) -->

<!-- rmarkdown::render(input = file.path(".","index.Rmd"), output_file =  file.path(".","_book","index"), output_format = "bookdown::gitbook", envir = new.env()) -->


<!-- Put in the console to render all the book in html -->
<!-- bookdown::render_book('index.Rmd', 'bookdown::gitbook') -->
<!-- Put in the console to render all the book in pdf. It creates file _main.index in folder _book with an the index -->
<!-- bookdown::render_book('index.Rmd', 'bookdown::pdf_book') -->
<!-- bookdown::render_book('index.Rmd', 'bookdown::pdf_document2') -->

<!-- TODO mirar: https://github.com/ismayc/thesisdown/blob/master/inst/rmarkdown/templates/thesis/skeleton/skeleton.Rmd -->
<!-- https://github.com/ismayc/thesisdown -->


<!-- Enable git in Rstudio -->
<!-- https://support.rstudio.com/hc/en-us/articles/200532077?version=1.4.1106&mode=desktop -->

<!-- Connect RStudio to Git and GitHub -->
<!-- https://happygitwithr.com/rstudio-git-github.html -->

# Abstract {-}

The eReuse.org federation develops a set of tools and methodologies to bootstrap reuse of digital devices and account its contribution to the circular economy. The intended impact is to extend device lifetime and increase proper recycling at the end of the useful lifetime. In this whitepaper we present the federation, the tecnological roadmap and  use cases that create value to consumers, refurbishers and recyclers. In the roadmap we present the conditions and capabilities required for verify traceability and impact accounting while while preserving privacy of consumers and businesses. The aim is to make replication easy for other regions and allow the interoperation with others systems with the purpose of make reuse/recycling and tech industry impact accountable. Ultimately empowering consumers to choose reparable, reusable and durable devices.


**Objectivo: **

* El del whitepaper es principalmente un documento introductorio para externos aunque también puede servir para colaboradores internos (proyectistas,...) que quieren iniciarse. 

* Un white paper es declarativo: como está, que debes entender para poder usar/participar,... [A la tesi expliques els perques i ho valides. La lógica, es un coneixment. Quina validació fas, dicussió.]

* Explicar los casos de uso y roadmap tecnológico necesario para llevarlos a cabo (que tenemos hoy y que queremos para el futuro)

**Capítulos:**

**capítulo I: Introducción.**

Que es eReuse, que objetivos tiene, quien forma parte

**capítulo II: Conceptos.**

A qui queremos explicar la visión de eReuse de la economía circular

**capítulo III: Impact and outcomes**

Descripción del impacto y outcomes.

**Capitol IV: Use cases.**

Poder conocer las preguntas generales y la útilidad. Expertos de EC puedan saber de que trata sin ir al detalle o tener que compartir la propuesta.

Descripción de los use cases pero no llegar a explicar la implementación/propuesta/detalle. Por ejemplo la figura 4.1 potser es massa detallada. POsar-ho un nou apartat al final: on estem i detall. 

Importante poder vislumbrar que building blocks, conditions or capabilities van a ser necesarias para poder implementarlo

Mirar document sobre w3i: Explicar les funcionalitats/requeriments i casos d'us. 

**capitulo V: Roadmap: building blocks, conditions or capabilities**

Asegurar la coherencia entre Capito anterior de casos de uso con este (que building blocks, conditions or capabilities) tal que creemos que són necesarios para poder responder a nuestros casos de uso.

Explicar a alto nivel lo que se necesita pero no explciar el como (implementación ejemplo como construimos el hardware id o el product passport). 

Information systems and tools
Circular economy accountability
Incentives for circularity

**capitulo VI: Technology**

Por ahora un listado de los repositorios que tenemos propios y legacy.



