# Credentials

TODO Imatge credentials en anglés

L’Acreditació de eReuse es compon d’un conjunt de mètriques i indicadors que formen part de ´’estàndard d’eReuse i que tenen com objectiu poder monitoritzar el rendiment i contribució del centre cap a un model de gestió més circular dels productes electrònics. En general, en un procés de certificació es requereix que una entitat tercera faci un procés d’auditoria per tal d’avaluar si les dades recollides i acreditades sobre el rendiment del centre ha seguit ´’estàndard. La nostra proposta és beneficiar-se de la tecnología blockchain per a poder millorar i optimitzar les auditories externes.

El present projecte permet als centres de reutilització incentivar la recollida d’equips a reacondicionar, així com la demanda dels reacondicionats. D’una banda, les empreses i l’administració pública poden conèixer la cadena de custodia dels dispositius que donen, saber si es reciclen o es reutilitzen, l’impacte que això genera i els tractaments que s’han fet, especialment l’esborrat segur de dades. En segon lloc, desde la òptima del comprador de segona mà, aquest podrà conèixer el procés de reacondicionat o de preparació per a la reutilització, amb un certificat de qualitat i la classificació del rendiment.

Els centres de reutilització reben el distintiu de eReuse.org i passen a formar part del Circuit Pangea si poden certificar: i) a Pangea (i en general als donants) la cadena de traçabilitat i l'impacte generat en economia circular i social, ii) als seus clients la qualitat del procés de reacondicionat o de preparació per a la reutilització. Per tant, el benefici és doble i mútuo, doncs al certificar la traçabilitat i l’impacte es millora la fidelització dels donants que té Pangea i per tant s’incrementen les donacions de dispositius que rep, i al certificar la qualitat del reacondicionat s’incentiva la demanda de dispositius a reacondicionar i per tant es generen majors beneficis per als centres de reutilització.

Les acreditacions d’eReuse són doncs un conjunt d’incentius per a donants i compradors. Aquesta informació és creïble donat que s’han emprat un conjunt d’eines que generen informació fiable del procés que es realitza sobre una base de dades que no permet la seva
modificació (la blockchain) fent així el procés auditable i comptabilitzable. En conclusió, gràcies al projecte s’ha pogut dotar als centres de reutilització de l’Economia Social i Solidària (ESS) d’una acreditació d’electrònica circular que els permet diferenciar-se vers les entitats que diuen que promouen la reutilització, però veritablement fan reciclatge prematur o exportació il·legal de productes o residus electrònics.

Com ja hem mencionat a la introducció, el projecte té per objectiu dotar als centres de reutilització de l’ESS d’un certificat/acreditació que els diferencien de les entitats que diuen que promouen la reutilització pero veritablement fan reciclatge prematur o exportació il·legal de productes o residus electrònics. Les certificacions d’eReuse fan aquesta funció de distinció.

En general, en un procés de certificació es requereix que una entitat tercera faci un procés d’auditoria per tal d’avaluar si les dades recollides i acreditades sobre el centre ha seguit l’estàndard d’eReuse. En aquesta acció, a més d’explicar el conjunt d’acreditacions d’eReuse, també introduïm les eines que utilitzen els centres per a generar/recollir les dades que posteriorment els centres auto-certificaran i Pangea i els donants auditaran/verificaran.

Les acreditacions eReuse són una distinció del centre que indica que està en disposició de poder recollir, certificar i ser auditat en: la qualitat dels dispositius que reacondiciona, la reutilització/reciclat dels dispositius que rep dels donants, i la capacitat per a poder contribuir a mesurar l'impacte social i circular. A més, si comparteix les dades de circularitat dels equips amb la comunitat eReuse també rep una acreditació addicional. En la figura 5 es mostren les acreditacions que eReuse ha definit amb col·laboració amb els centres de reutilització federats. Consten de quatre que s’obtenen en la mesura que els centres tenen la capacitat d’oferir dades
de qualitat del reacondicionat, informar de l'impacte i la traçabilitat dels equips que reben, i comparteixen les dades de circularitat de manera anonimitzada amb el repositori open-data de eReuse.

## Refurbishment quality

Per a incentivar el consum de segona mà dels dispositius digitals cal promoure l'excel·lència del
procés de reacondicionat dut a terme pels centres de reutilització. La taula de la figura 1,
presenta la informació que els consumidors volen tenir alhora de comprar un dispositiu de egona mà. Per ordre de prioritats del tercer al cinquè lloc, el consumidor vol estar informat en
"3: classificació", "4:Informació del procés de reacondicionat, i "5: Certificat de qualitat".
En termes generals el consumidor ha de poder confiar en que la informació del dispositiu que
ofereix el centre de reutilització ha estat generada de manera segura i no ha estat alterada. La
informació a mostrar ha de complir amb els següents requisits:
1. Generació: Les dades han estat generades de manera automàtica i segura amb un
programari que s’ha executat al dispositiu reacondicionat. El resultat de l’execució del
programari es publica directament al web del dispositiu.
2. Modificació: Les dades no són modificables manualment. En el cas que la qualitat del
dispositiu o algun dels seus components hagi variat, s’hauria de tornar a executar el
programari pel punt anterior.
3. Accés obert: Les dades han de ser accessibles via un enllaç web que no ha de requerir
un usuari i clau, a més també s’hauria de permetre accedir via un codi QR adherit al
dispositiu que enllaça a la web del dispositiu.
A mode d’exemple, a la següent pàgina web consta un dispositiu que ha estat reacondicionat
per un centre de reutilització. La informació inclou els tres aspectes que formen part de la
descripció de la qualitat del reacondicionat, que són: 1.1: Especificacions, 1.2: Classificació i
1.3: Procés de reacondicionat. A més el centre compleix amb els tres requisits de generació,
modificació i accés obert:

A mode d’exemple, a la següent pàgina web consta un dispositiu que ha estat reacondicionat
per un centre de reutilització. La informació inclou els tres aspectes que formen part de la
descripció de la qualitat del reacondicionat, que són: 1.1: Especificacions, 1.2: Classificació i
1.3: Procés de reacondicionat. A més el centre compleix amb els tres requisits de generació,
modificació i accés obert:

https://api.usody.com/usody/devices/2DBZ9
Figura 6: Pàgina web pública del dispositiu
A l’enllaç web també s’hi pot accedir via la lectura d’un codi QR que està adherit al dispositiu:

Figura 7: Codi QR enllaçant a la pàgina web

### Especificacions
A la pàgina web del dispositiu almenys ha de constar 8 la marca del fabricant i model del
dispositiu. En l’exemple presentat, es pot identificar que es tracta d’un dispositiu de marca
(“Manufacturer”) Fujitsu, (“model”): Esprimo e500 i de tipus escriptori (“Tower”).

Figura 8: Característiques del dispositiu

A la web del dispositiu també s’hi han de mostrar els seus principals components. En el cas
d’un dispositiu de tipus escriptori volem saber: el processador (intel core i7) la memoria RAM
(8GB), la memoria del disc dur (Data storage - 500 GB), la tarjeta gràfica i si disposa de tarja de
xarxa.

Figura 9: Característiques dels components


### Classificació

A la pàgina web també ha de constar una classificació del dispositiu. En el nostre cas, utilitzem un algoritme, (Franquesa, 2018) 9 que dona una puntuació de 0 a 5 en base a les comparatives dels dispositius registrats al sistema. Els dispositius que tenen unes prestacions de rendiment acceptables per a ser reutilitzables reben una puntuació superior a tres (Total Rate). Els principals components també són avaluats per separat.

Figura 10: Puntuació del disc dur

Figura 11: Puntuació de la memòria RAM

Figura 12: Puntuació del processador.

Figura 13: Puntuació total del dispositiu

### Procés de reacondicionat

A la pàgina web es mostra el procés de reacondicionat realitzat pel centre de reutilització i els resultats dels tests de funcionament, tant a nivell de component com de dispositiu. Amb l’objectiu de permetre la verificació per part del consumidor, també s’indica quin programari i versió ha estat emprat per a fer el tests de funcionament, tal que el consumidor pot reproduir el procés per validar que els resultats són els indicats en el moment de la seva compra.

Figura 14: Registre del procés de reacondicionat

## Informes de reutilització i reciclatge

Els centres de reutilització federats a eReuse han d’estar en disposició de poder emetre un
informe als seus donants sobre la traçabilitat i l’impacte en economia circular, tant ambiental
com social, dels dispositius que han rebut. Principalment, per a cada dispositiu que rep un
centre, ha d’informar si l’ítem en qüestió ha acabat sent reciclat o reutilitzat. Aquest informe
l’emeten directament als seus donants o ho fa Pangea en cas de que sigui aquesta última la que
els ha derivat des del Circuit Pangea. Per tal de poder traçar un dispositiu ens cal poder generar
un identificador que sigui únic a nivell global i autogenerable. A aquest identificador
l’anomenem el passaport del dispositiu.

### Passaport del dispositiu

El passport del dispositiu permet als centres de reutilització, i les seves col·laboradores (distribuidores i consumidores finals), fer la traçabilitat dels productes reutilitzats i poder informar de si finalment s’han reciclat en un centre gestor de residus. Per a que eReuse consideri que el centre de reutilització està usant un passaport de dispositiu, aquest ha de complir que sigui únic a nivell global i autogenerable en base el maquinari. 

#### Conceptes preliminars

eReuse considera que el passaport és vàlid si el procés de creació del passaport s’ha fet fent ús d’eines que recullen informació invariable del dispositiu fent una lectura directa sobre el maquinari. A aquest identificador l’anomenem l’identificador del maquinari. 

Els valors necessaris per a crear un identificador de maquinari únic són: i) la marca, ii) el model, iii) el número de sèrie i iv) l’identificador de la targeta de xarxa del dispositiu. A partir d’aquests quatre identificadors podem assegurar que l’identificador és únic a nivell global. Per exemple el següent identificador


desktop-hewlett-packard-hp_compaq_8000_elite_sff-czc038bqt9-00:23:24:13:a5:37
Figura 15: Identificador únic del maquinari

Al recollir aquesta informació mitjançant eines de programari que la poden llegir, podem
assegurar que un dispositiu sempre tindrà un identificador de maquinari únic. Aquest
identificador, abans d’enviar-se a eReuse, és anomitzat. El procés d’anonimització es fa
mitjançant una funció resum 10 (o hash). Com a resultat d’aplicar la funció de hash (en aquest
cas la SHA-256), l’ identificador de maquinari únic i anonimitzat resultant ha estat:
e71f2e95da5455b4d8d27077b7b9e1919df918d11e7b69a2905f7da14cd35359
Figura 16: Identificador únic del maquinari anonimitzat

#### Generació del número de passaport.

A partir de l’identificador de maquinari amb la funció de hash aplicada (figura 16) del pas anterior farem tot un seguit de passos per a crear un número de passaport que sigui fàcilment llegible per als centres de reutilització, les col·laboradores i les usuàries finals que l’hauran de portar a un punt autoritzat per fer-ne el reciclatge. eReuse defineix un protocol per a crear aquest passaport però alhora també posa a disposició les eines necessàries en programari lliure
que expliquem a continuació.

10 És un algorisme o funció per sumaritzar https://ca.wikipedia.org/wiki/Funció_hash per detalls).

1. Registre al sistema d’inventaris. El centre de reutilització ha de registrar el dispositiu amb unes eines que recullen informació invariable del maquinari i aplicar una funció establerta de hash. eReuse posa a disposició tant les eines per recollir la informació
com el sistema de traçabilitat d’inventaris.

2. Creació d’un número de passaport no vinculat. El centre de reutilització crearà al seu sistema d’inventaris una etiqueta de tipus passaport de producte. Ha d’anar a l’opció “tags” de tipus “unnamed tags” (veure següent figura). En aquest moment es fa una
petició al sistema de passaports d’eReuse i aquest li retorna un número de passaport únic (per exemple: DFR53). Aquest número encara no té cap dispositiu assignat. 

3. Vinculació d’un passport a un dispositiu. Al seu sistema d’inventaris, el centre selecciona el dispositiu i el número de passaport que li vol assignar. I envia aquesta informació (identificador de maquinari anonimitzat amb la funció de hash i el número de passport). El sistema de passports d’eReuse fa aquest vincle. És clau que la informació quedi anonimitzada per tal que eReuse no pugui saber de quin dispositiu en realitat es tracta.

4. Regeneració del número de passaport. si les consumidores finals o nous centres de reutilització / reciclatge extreuen l’etiqueta amb el número de passaport, ha de ser posible autogenerar el número inicial. El procés de regeneració és similar a l’anterior,
però en aquest cas, quan el nou usuari vulgui associar el dispositiu amb el número de passaport, el sistema de passaports d’eReuse li farà saber que ja existeix 11 un número de passaport per aquell dispositiu i li retornarà.

Figura 17: Creació del passaport del producte

### Informe de reutilització
Els donants de dispositius principalment volen saber si els dispositius s’han reutilitzat o reciclat. Dels dispositius reutilitzats, en concret, volen saber a quina entitat consumidora s’han destinat i quin import ha hagut d’assumir. L'import és molt rellevant en el cas dels circuit Pangea doncs s’estableix que aquest hauria de ser similar al de la suma del cost de recollida,
emmagatzemament, reacondicionat, distribució, traçabilitat i informe d’impacte. Altre
informació que hauria d’introduir-se per a poder fer l’informe seria poder saber el segment de
consumidors i el nombre d’usuaris estimats que faran ús dels dispositius.
eReuse considera que aquesta és la informació material d’un informe de reutilització i posa a
disposició dels centres de reutilització un sistema d’inventaris i de traçabilitat per introduir la
informació i per a generar un informe de reutilització:

11. Si l'identificador de maquinari és el mateix, el resultat d’aplicar la funció de hash donarà el mateix
resultat.

Figura 18: Traçabilitat de l’acció de reutilització

El sistema d’inventaris eReuse permet definir l’acció “Allocate”, que significa que un dispositiu ha passat a ser reutilitzat (veure figura 18). En la descripció de l’acció “Allocate” (veure figura 19) les dades més rellevants són: i) la data de transferència del dispositiu (start date), ii) la transaction (el codi de transacció anònim de referència per si el centre de reutilització rep una
auditoria del donant o de Pangea), iii) el segment d’usuaris finals que faran ús dels dispositius (Final user Code), i iv) el número d’usuaris finals estimats que faran ús del dispositiu (Number Final Users). Aquesta informació és privada pel que queda anonimitzada a partir de l’identificador (transaction).

Figura 19: Introducció d’informació de reutilització

En el moment que el donant o Pangea ho requereixi, el centre de reutilització pot generar un
informe de reutilització amb la relació dels dispositius que ha rebut del donant i el seu estat,
reutilitzat o reciclat.

Per a generar l’informe a un donant, s’ha de seleccionar els equips del donant que estan en
reutilització. En la següent figura s’han seleccionat tots els dispositius d’un donant en particular
i això mostra tots els dispositius (veure figura 21).

Figura 20: Lots de reutilització d’un donant

Mitjançant l'opció Export-> Metrics Spreadsheet es genera una fulla excel on figura l’estat de
cadascun dels dispositius que pot ser reutilitzat o reciclat.

Figura 21: Dispositius en reutilització d’un donant en particular


Figura 22: Informe de dispositius en reutilització

En la figura 22 es mostra com tots els dispositius estan en reutilització

### Informe de reciclatge
El sistema eReuse permet definir l’acció “Deallocate”, que significa que un dispositiu ha deixat
d’estar en estat reutilització. En aquesta acció indicarem una data i un codi de transacció que
pel centre de reutilització significa el seu reciclatge.

Figura 23: Introducció d’informació de reciclatge

Seguint un procés similar al de l’informe dels dispositius en reutilització, generem un informe
de reciclatge.

En l’acció 2 explicarem com els centres de reutilització fan el procés de certificació d’aquesta
informació i com els donants i Pangea en poden fer l’auditoria


## Compartir la circularitat dels models de dispositius

Els centres de reutilització que comparteixen amb eReuse les dades per a mesurar la vida útil dels dispositius reben aquesta acreditació. A continuació expliquem quatre conceptes que ens ajudaran a entendre la importància de compartir aquestes dades amb la comunitat eReuse.

1. La vida útil potencial: la vida útil potencial d’un dispositiu és el temps des del llançament o data fabricació del dispositiu fins que es recull per al seu reciclatge. En l’exemple de la figura 24, la vida útil potencial seria de 9 anys. Per a poder-ho calcular necessitem que el centre de reutilització ens cedeixin la data de registre en el seu centre.

2. La vida útil: la vida útil d’un dispositiu és el temps des de la venda del producte fins al moment en què es descarta. En l’exemple de la figura 24, seria de 6 anys (2 primer cicle d’ús + 4 segon cicle d’ús). Per a poder-ho calcular necessitem dues dates, la data que es va vendre 12 a l’usuari i la data que l’usuari se’n va desfer 13 .

3. Les hores de funcionament: les hores de funcionament d’un dispositiu són les hores que ha estat engegat (Powered On). En l’exemple de la figura 25 serien 40.000 hores. Per a poder-ho calcular necessitem que el centre de reutilització faci una lectura del
valor Powered-On-Hours 14 del disc dur.

4. Les hores d’apagat: Les hores d’apagat d’un dispositiu són les hores que ha estat apagat (Powered Off). Les hores s'obtenen de la diferència d’hores de la vida útil del dispositiu i les hores Powered on.


Figura 24: Vida útil potencial i vida útil d’un dispositiu

12 La data de venta a l’usuari consumidor: data en que el dispositiu es ven a un usuari. En en cas que sigui de segona mà i es tracti d’un centre de reutilització federat a eReuse tindrem aquesta data. Si no tenim la certesa de tenir aquesta data, agafarem la data de fabricació.

13 La data en que el consumidor se’n desfà: la inferim a partir de la data del darrer accés a disc.

14 Hores en engegat (POH): durada en hores que un dispositiu està engegat. https://en.wikipedia.org/wiki/Power-on_hours


Figura 25: Hores en funcionament (Powered on) i hores en apagat (Powered Off)

A partir de les dades anteriors, els membres federats a eReuse poden millorar el procés de
filtratge dels dispositius que reben identificant millor els que tenen un major potencial de
reutilització. En la figura 26 hi ha un exemple d’anàlisi de durabilitat del model de dispositiu
Acer Veriton M480 per al que tenim 200 observacions. Es pot identificar que hi ha un dispositiu
que ha superat les 65 mil hores i que la vida útil potencial és, de mitjana, d’uns 8 anys. La
utilitat d’aquesta informació per al centre és que en cas de rebre dispositius del model amb
menys de 10 mil hores, es pot establir que probablement estaran en funcionament almenys 10
mil hores més. Fent una analogia amb la compra de segona mà dels cotxes seria com saber els
quilòmetres que ha recorregut el cotxe que et vols comprar. Aquesta informació també es pot
fer pública de forma agregada per a que els consumidors sàpiguen la durabilitat dels models i
ho tinguin en compte alhora de comprar-se un equip nou.

Figura 26: Análisis de la potencial vida útil d’un dispositiu Acer model Veriton M480

## Mesurar l'impacte social i circular.

La darrera certificació és la capacitat del centre de reutilització de poder oferir les dades per a mesurar l'impacte social i circular dels dispositius que rep. A partir de la informació recollida pel seu sistema es pot generar un informe d’impacte. Enguany estem treballant en la generació d’aquests informes que es generaran amb la informació recollida en els passos anteriors:

1. Ambiental: dispositius reutilitzats i reciclats, components reutilitzats, extensió de la vida útil i localitat de reutilització/reciclatge 

2. Social: extensió de la vida útil, tipologia del centre de reutilització, segmentació dels beneficiaris

3. Econòmic: import de la venta







